//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S02_04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPersonal
    {
        public int codEntrada { get; set; }
        public string nombreEmpleado { get; set; }
        public int identificacion { get; set; }
        public string posicion { get; set; }
        public string area { get; set; }
        public string fechaEntrada { get; set; }
        public string horaEntrada { get; set; }
        public string fechaSalida { get; set; }
        public string horaSalida { get; set; }
    }
}
