//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S01_01Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Perfiles = new HashSet<Perfiles>();
        }
    
        public string nombreUsuario { get; set; }
        public string pass { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuario1 { get; set; }
        public virtual ICollection<Perfiles> Perfiles { get; set; }
    }
}
