//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S04_04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfile
    {
        public Perfile()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int codPerfil { get; set; }
        public string nombrePerfil { get; set; }
        public bool activo { get; set; }
    
        public virtual Perfile Perfiles1 { get; set; }
        public virtual Perfile Perfile1 { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
