//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S03_04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPersonas
    {
        public int identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int edad { get; set; }
        public string correo { get; set; }
        public int tetefono { get; set; }
        public string pais { get; set; }
        public string ciudad { get; set; }
        public string detalles { get; set; }
    }
}
